### ISSUE TITLE
Compilation issue for all 3 C Programs

### ISSUE THREAD

**Issue by matteog** [andy-west/consolized-game-boy#1]
Hello.

For some reason I can’t compile any of the 3 C programs in the src folder. I can run cmake, but as soon as I run make, there’s an error. It states:

fatal error: cannot read spec file ‘noses.specs’: No such file or directory.

The example vga program from the example program does work just fine, however. Also, I am compiling the programs on a pi zero 2nd generation. 

Thanks.

**Comment by andy-west** [comment]
This code is for the Raspberry Pi Pico, not the Pi Zero. It will not work on any other Pi than the Pico because it's a microcontroller and not a single-board computer.

**Comment by matteog** [comment]
Ok but before uploading the code to the pico I have to compile it, get the ulf file, and then upload the code to the pico. I can’t get to the ulf stage. I should’ve been more descriptive in my question. Sorry about that. Thanks.

**Comment by andy-west** [comment]
I see what you're saying. I've only ever tested this on the Raspberry Pi 4, and only with a clean install. I'm unable to support other devices/platforms.

I've never heard of "noses.specs". nosys.specs, maybe?

My best possible guess is that newlib is missing for some reason. Here is a link with a similar issue: https://forums.raspberrypi.com/viewtopic.php?t=300186

**Comment by matteog** [comment]
You are right. It is indeed nosys.spec. It got autocorrected in my original post lol. I will take a look at the link. If I am successful maybe I can add a how-to for the raspberry pi zero. If not I will try to compile it on a raspberry pi 4 with a clean install. Thanks again.

**Comment by andy-west** [comment]
> If I am successful maybe I can add a how-to for the raspberry pi zero.

That would be awesome! Sorry I don't have time to add support for other systems myself. Good luck, and let me know how it goes. I always like to see other people's projects.
